Adding Location Search
adw0rd/instagrapi pull request #100
Opened 2021-02-11 22:07 UTC by jhd3197

2021-03-16 08:47 UTC, adw0rd commented
1. Why need storyUpload in photo_upload? Use photo_upload_to_story for uploading photo to story
2. extract_locationV2 - broken naming in the project (use extract_location_v2)
3. Error using private requests in a public module, this makes no sense (You use private_request in public.py module)
4. The rest of the functions for working with GEO (location) will still need to be checked, I did not see any tests on them

2021-03-16 08:48 UTC, adw0rd requested changes
1. Why need storyUpload in photo_upload? Use photo_upload_to_story for uploading photo to story
2. extract_locationV2 - broken naming in the project (use extract_location_v2)
3. Error using private requests in a public module, this makes no sense (You use private_request in public.py module)
4. The rest of the functions for working with GEO (location) will still need to be checked, I did not see any tests on them

2021-03-16 08:49 UTC, adw0rd requested changes

2021-03-16 08:49 UTC, adw0rd commented on README.md
> +* `storyUpload`  - If True will create a story from image (default: False)
Why need storyUpload in photo_upload? Use photo_upload_to_story for uploading photo to story

2021-03-16 08:49 UTC, adw0rd commented on instagrapi/mixins/public.py
> +        response = self.private_request(url, params=params)
Error using private requests in a public module, this makes no sense (You use private_request in public.py module)

2021-03-16 08:49 UTC, adw0rd commented on instagrapi/extractors.py
> +    """Extract location info"""
extract_locationV2 - broken naming in the project (use extract_location_v2)

2026-04-15 18:50 UTC, subzeroid commented
Thanks for the early location-search work here. I did not merge this old branch directly because it also carried unrelated and already-rejected changes, but I did salvage the useful location-search part onto current master in a clean form: location_search_name(...), location_search_pk(...), proper top_search place/location extraction, docs, and focused regression coverage. Closing this old PR as superseded by that modernized implementation.

2026-04-15 18:50 UTC, closed without merging