Changed the HD Profile Picture value - user_info_by_username_v1
adw0rd/instagrapi pull request #1083
Opened 2023-01-26 13:54 UTC by ashirali4

I have added this code 

![image](https://user-images.githubusercontent.com/38634960/214852773-0429ba5c-6b42-451d-b30f-0ef622a00827.png)

Instead of this 

![image](https://user-images.githubusercontent.com/38634960/214852818-5559f3ed-e86b-4f13-aef0-6140842cd411.png)
Fetching the hd version from the second one first, anyways I am new to py and flask so unable to find it in `user_info_by_username()`

Anyways I have added here `user_info_by_username_v1()`

Do check and let me know what we can do @adw0rd

2023-01-26 14:50 UTC, adw0rd requested changes

2023-01-26 14:50 UTC, adw0rd commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
Тут будет ошибка в случае `pic_hd = data.get("hd_profile_pic_url_info")`, так как это не список, а словарь

2023-01-26 14:50 UTC, adw0rd commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
Why `pic_hd[1]`?  Maybe `pic_hd[2]`?

Maybe you need to sort first? For example like this:

`sorted(pic_hd, key=lambda o: o["height"] * o["width"])[-1]["url"]`

2023-01-26 14:53 UTC, ashirali4 commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
I have reviewed them, and they are already sorted on the basis of height and width.

2023-01-26 14:53 UTC, ashirali4 commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
and getting max 0,1 two image object not more than that.

2023-01-26 14:55 UTC, ashirali4 commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
I'll fix this as the profile_pic_url_hd is an array and otherone is dict.

2023-01-26 15:10 UTC, ashirali4 reviewed
There will be an error in the case of pic_hd = data.get("hd_profile_pic_url_info"), since this is not a list, but a dictionary - Fixed.

2023-01-26 15:11 UTC, ashirali4 commented on instagrapi/extractors.py
> +        data["profile_pic_url_hd"] = pic_hd[1].get("url") or pic_hd.get("url")
![image](https://user-images.githubusercontent.com/38634960/214872299-a1dbde0a-a623-4025-aa01-f5d418c78aa8.png)

2023-01-27 20:00 UTC, ashirali4 commented
any update @adw0rd

2023-01-27 20:12 UTC, merged

2023-01-27 20:36 UTC, adw0rd commented
@ashirali4 I rewrote your code

https://github.com/adw0rd/instagrapi/commit/7cfaaef26421edb32d3fbbc3e4352afd02eef2fd