fix for user info (user info gql)
adw0rd/instagrapi pull request #1868
Opened 2024-04-09 19:12 UTC by SaeidB

__a=1&__d=dis no longer work , replaced with web_profile_info

2024-04-10 10:39 UTC, claell commented
While you probably found the correct workaround, this doesn't seem to be compatible with the already existing methods and setup of instagrapi.

@subzeroid (or @tajbowness), as this is a rather important problem, do you possibly have the time to look into fixing this, based on this PR? The solution itself looks pretty easy and just needs to be fit into the existing code base.

2024-04-10 10:52 UTC, SaeidB commented
> While you probably found the correct workaround, this doesn't seem to be compatible with the already existing methods and setup of instagrapi.
> 
> @subzeroid (or @tajbowness), as this is a rather important problem, do you possibly have the time to look into fixing this, based on this PR? The solution itself looks pretty easy and just needs to be fit into the existing code base.

What do you mean ? Did you try and got any error ? I tried it and worked for me without any problem, the native public request of Instagrapi uses __a=1 and i bring plane requests to this part to fix it, you can use "extract_gql..." or not, i comment that line, if you use commented line, the result is exactly the same as before, you can easily get user info without need of login

2024-04-10 11:03 UTC, claell requested changes
I reviewed your code to highlight the current problems.

Of course, I am sure that it works right now. It is just not fitting the project structure and thus creating new issues and maintainability problems if it's merged like this.

Let me know if you need more help with refactoring your code.

2024-04-10 11:03 UTC, claell commented on instagrapi/mixins/user.py
> +        return requests.get(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers=headers, verify=False, proxies = {'http' : self.proxy, 'https':self.proxy}).json()
Why do you use the plain requests library here? There are already existing requests methods in the project that should be used. This allows users to control arguments of the functions and make whole logics much more generalizable. Look at the previous implementation and try to start from there.

2024-04-10 11:03 UTC, claell commented on instagrapi/mixins/user.py
> +
This newline is not needed.

2024-04-10 11:09 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        #return extract_user_gql(requests.get(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers=headers, verify=False, proxies = {'http' : self.proxy, 'https':s
not needed, removed

2024-04-10 11:11 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
the new endpoint for user info need some new headers and user-agent and the old headers wont work , this is the reason i put headers directly , and instagrapi users wont need to change headers in gql requests like this request , so the better idea is to use headers directly in endpoints like this , understood ?

2024-04-10 11:12 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        return requests.get(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers=headers, verify=False, proxies = {'http' : self.proxy, 'https':self.proxy}).json()
the new endpoint for user info need some new headers and user-agent and the old headers wont work , this is the reason i put headers directly , and instagrapi users wont need to change headers in gql requests like this request , so the better idea is to use headers directly in endpoints like this , understood ?

2024-04-10 11:12 UTC, SaeidB commented
the new endpoint for user info need some new headers and user-agent and the old headers wont work , this is the reason i put headers directly , and instagrapi users wont need to change headers in gql requests like this request , so the better idea is to use headers directly in endpoints like this , understood ?

2024-04-10 11:28 UTC, claell commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
Mh. But just giving new headers hard coded is not a clean way to go in that case, either. This might also result in Instagram banning clients, if they see requests with different headers from the same IP.

So, how do the new headers differ from the old expected ones? Can they somehow get translated into each other? Or be set explicitly somewhere, like the old headers?

2024-04-10 11:32 UTC, claell commented
I hope, you understand my points. Hardcoding values like this and not relying on existing functions is in general a bad practice (maintainability, generalizability, ...).

I got it that the endpoint probably requires different requests, so in that case, probably the way to go is to generalize the existing functions for the new use cases.

2024-04-10 11:37 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
as i said this is a public request (gql , or non auth request) , and the headers are same everytime you send request , even the current model uses same headers everytime (for public request) ( monitor the instagrapi requests so you can see ) , so instagram will not ban you ,

2024-04-10 11:39 UTC, SaeidB commented
> I hope, you understand my points. Hardcoding values like this and not relying on existing functions is in general a bad practice (maintainability, generalizability, ...).
> 
> I got it that the endpoint probably requires different requests, so in that case, probably the way to go is to generalize the existing functions for the new use cases.

as i said this is a public request (gql , or non auth request) , and the headers are same everytime you send request , even the current model uses same headers everytime (for public request) ( monitor the instagrapi requests so you can see ) , so instagram will not ban you , rotating requests is for private request ( authenticated requests , my pr is for non authenticated request for user info ) , now do you understand ?

2024-04-10 11:41 UTC, SaeidB commented
> I hope, you understand my points. Hardcoding values like this and not relying on existing functions is in general a bad practice (maintainability, generalizability, ...).
> 
> I got it that the endpoint probably requires different requests, so in that case, probably the way to go is to generalize the existing functions for the new use cases.

as i said this is a public request (gql , or non auth request) , and the headers are same everytime you send request , even the current model uses same headers everytime (for public request) ( monitor the instagrapi requests so you can see ) , so instagram will not ban you , rotating headers is for private request ( authenticated requests , my pr is for non authenticated request for user info ) , now do you understand ?

2024-04-10 11:42 UTC, claell commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
No, if I set a different user agent, this won't get used for this request. Also, and I repeat, hardcoding the header here is the wrong place.

I am happy to assist you with improving the code quality. But I hope, you can understand why this is not good coding style.

2024-04-10 11:49 UTC, claell commented
Here, you can see the current setup: https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L209. You can possibly also create a new function there (if needed) and then rely on that one. Please note that there is also already a function for public requests: https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L77.

2024-04-10 11:51 UTC, SaeidB commented
> Here, you can see the current setup:
> 
> https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L209
> 
> . You can possibly also create a new function there (if needed) and then rely on that one. Please note that there is also already a function for public requests:
> https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L77
> 
> .

this is for __a=1 , they removed that

2024-04-10 11:53 UTC, SaeidB commented
check the instagrapi gql requests , the headers are same everytime , it uses its own user agent , not logged-in client user agent (mobile), not base_headers , if you use another user agent for this request , it will return you "mismatch user agent error etc"

2024-04-10 11:57 UTC, claell commented
My main argument stands. Hard coding this like you did is not good practice. Also, there is no error handling for the request.

The already existing functions provide that already. So, I hope, you can find a way how to rely on them (or refactoring them appropriately). I will be of help, if needed.

2024-04-10 12:01 UTC, SaeidB commented
> My main argument stands. Hard coding this like you did is not good practice. Also, there is no error handling for the request.
> 
> The already existing functions provide that already. So, I hope, you can find a way how to rely on them (or refactoring them appropriately). I will be of help, if needed.

you can see hard-coded by the author in the link below, no problem in public request to hard-code headers 
https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L69

2024-04-10 12:03 UTC, claell commented
I meant hard coding like you did. You hard coded this in the wrong place, where it can't be reused. There is no error handling, no reliance on good, already existing functions.

2024-04-10 12:04 UTC, SaeidB commented
> My main argument stands. Hard coding this like you did is not good practice. Also, there is no error handling for the request.
> 
> The already existing functions provide that already. So, I hope, you can find a way how to rely on them (or refactoring them appropriately). I will be of help, if needed.

you can see hard-coded by the author in the link below, no problem in public request to hard-code headers

https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L69

thats why i told you to check instagrapi public requests in mitm 

thank you for your contribution

2024-04-10 12:05 UTC, claell commented
(You can also edit GitHub comments, no need to delete and send a new one)

2024-04-10 12:07 UTC, claell commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
`'X-Ig-App-Id': '936619743392459'` seems to be personalized and might cause problems in the header when used by all users of instagrapi.

2024-04-10 12:09 UTC, SaeidB reviewed
thats not personalized , its app id

2024-04-10 12:09 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
thats not personalized , its app id

2024-04-10 12:20 UTC, claell commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
You seem to be right, I found this very ID several times on the internet, and it appears to be working. In general, this ID might be thought to be personalized, for normal API users, though?

2024-04-10 12:29 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-M
what do u mean ? its something like bloks versioning id in instagram APK and is not personalized..
https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/auth.py#L294
https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/private.py#L170

2024-04-11 08:28 UTC, claell commented
Here, you can see some part of the already existing request error handling code:

https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L190C1-L202C54

So I hope this helps you understand, why it is important to rely on existing functions and why just using `requests` like you did is not error prone.

2024-04-11 16:01 UTC, claell commented
Already better. But still needs some more refactoring, from my perspective.

One possible problem now is this line:

https://github.com/subzeroid/instagrapi/blob/b83a00b6d5c23029d9ab22b573ef26ebc79ef262/instagrapi/mixins/public.py#L130C13-L130C48

Not sure, but probably we don't want to update the internal headers with the ones that are only used for that request?

Additionally, probably some more refactoring is sensible (like moving the custom headers to a different place. Defining them here like you do is not really sensible, as it won't allow any other functions to make use of them.).

2024-04-11 16:08 UTC, SaeidB commented
> Not sure, but probably we don't want to update the internal headers with the ones that are only used for that request?\n\nAdditionally, probably some more refactoring is sensible (like moving the custom headers to a different place. Defining them here like you do is not really sensible, as it won't allow any other functions to make use of them.).

Correct we don't need to use these headers on the other methods so make sense to pass them directly to the self.public_request instead of update the headers

2024-04-12 09:16 UTC, claell commented
Try to have a look at my referenced line again. It shows that if headers are passed to `public_request`, the headers will then get updated (which is not wanted). So that needs to be slightly refactored, probably.

2024-04-12 10:25 UTC, SaeidB commented
> Try to have a look at my referenced line again. It shows that if headers are passed to `public_request`, the headers will then get updated (which is not wanted). So that needs to be slightly refactored, probably.

yeah i got you , 
```
default_public_headers = self.public.headers
temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392459','Sec-Ch-Ua-Model': '""','Sec-Ch-Ua-Mobile': '?0','User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36','Accept': '*/*','X-Asbd-Id': '129477','Sec-Fetch-Site': 'same-origin','Sec-Fetch-Mode': 'cors','Sec-Fetch-Dest': 'empty','Referer': 'https://www.instagram.com/','Accept-Language': 'en-US,en;q=0.9','Priority': 'u=1, i'}
data = extract_user_gql(json.loads(self.public_request(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers=temporary_public_headers))['data']['user'])
self.public.headers.update(default_public_headers)
return data
```

2024-04-12 10:54 UTC, claell commented
Your solution fixes the problem, but I think, there is a better way:

Refactoring some functions in `public.py`.

Why? Because I am rather confident that the headers will be needed for other calls as well in the future. So one possible suggestion would be adding another function similar to `public_a1_request` in `public.py`.

That function will have the headers (there, they can probably be hardcoded, then), and it will call `public_request` in a similar manner, as you showed in your code.

I suggest though, to also refactor `public_request` and `_send_public_request` with an additional parameter `update_headers=True`. Then, you can set this parameter to `False` in your calls and that will prevent updating the headers in the first place (which seems to be cleaner, compared to setting them first and then reversing that afterwards).

This was kind of what I had in mind all along, and I thought, it was rather obvious, but apparently, my suggestions weren't clear to you, before.

What do you think?

2024-04-12 12:47 UTC, SaeidB commented
check the changes i made now , i added update_headers=False and i think everything is good now and enough for this step

2024-04-16 13:06 UTC, claell requested changes

2024-04-16 13:06 UTC, claell commented on instagrapi/mixins/public.py
> -            self.public.headers.update(headers)
Why don't you set `update_headers` to `False` by default everywhere? Would make things easier, then you just need to check if it's `True`.

2024-04-16 13:06 UTC, claell commented on instagrapi/mixins/public.py
> +            elif update_headers == False :
Not needed, it does nothing.

2024-04-16 13:06 UTC, claell commented on instagrapi/mixins/user.py
> +        update_headers = False
I think, you can set this in the function call, no need to create a variable before.

2024-04-16 13:06 UTC, claell commented on instagrapi/mixins/user.py
> +        temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392
This is my main critique: Why do you set the headers here? That way, they are bound to this function. No other functions can easily make use of them. So my suggestion is (again) to transfer this to a new request function in `public.py`.

2024-04-16 15:18 UTC, SaeidB commented on instagrapi/mixins/public.py
> +            elif update_headers == False :
actually it does , check more .

2024-04-16 15:20 UTC, SaeidB commented on instagrapi/mixins/public.py
> -            self.public.headers.update(headers)
i think this is better and no need alot of edits

2024-04-16 15:21 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        update_headers = False
just for clean coding

2024-04-16 15:21 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392
no other functions need these headers

2024-04-16 16:16 UTC, claell commented on instagrapi/mixins/public.py
> -            self.public.headers.update(headers)
Can you elaborate? I don't understand. Your solution seems to use more lines of code and is less intuitive to understand.

2024-04-16 16:16 UTC, claell commented on instagrapi/mixins/public.py
> +            elif update_headers == False :
The `elif` statement just passes. So it is not needed ;)

2024-04-16 16:17 UTC, claell commented on instagrapi/mixins/user.py
> +        update_headers = False
Alright, to me, the other way would look cleaner. But maybe subjective.

2024-04-16 16:18 UTC, claell commented on instagrapi/mixins/user.py
> +        temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392
They will! There are already open issues about other functions in instagrapi failing (I think there was one to get followers of a user), for example.

So I expect other functions needing similar workarounds as your PR in the future. If you have reasons to disagree, I am happy to learn them!

2024-04-23 13:37 UTC, SaeidB commented on instagrapi/mixins/public.py
> +            elif update_headers == False :
i prefer to write it ( elif ) for future usage

2024-04-23 13:39 UTC, SaeidB commented on instagrapi/mixins/user.py
> +        temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392
other upcoming methods will need different headers , they might not be exactly the same , in this step my model is good and can be used.

2024-04-23 17:17 UTC, claell commented on instagrapi/mixins/user.py
> +        temporary_public_headers = {'Host': 'www.instagram.com','X-Requested-With': 'XMLHttpRequest','Sec-Ch-Prefers-Color-Scheme': 'dark','Sec-Ch-Ua-Platform': '"Linux"','X-Ig-App-Id': '936619743392
Not sure whether that statement is sound. I am sure the approach can benefit from generalization!

2024-04-23 17:18 UTC, claell commented
@subzeroid, can you give a review and possibly make some calls on discussed topics?

2024-05-01 23:11 UTC, marek-knappe commented
Just add one thing, hardcoding user-agent can lead to auto-detection of the bot on the Instagram-side so I would recommend actually making it exactly the same globally for every request or at least being able to set it as a config variable.
Also having that variable (temporary_public_headers) globally available (instead of having it in the user scope)  would help if we will have any other request that will need to use it  - but that can be tomorrow's problem :)

2024-05-02 05:26 UTC, SaeidB commented
> Just add one thing, hardcoding user-agent can lead to auto-detection of the bot on the Instagram-side so I would recommend actually making it exactly the same globally for every request or at least being able to set it as a config variable.
> Also having that variable (temporary_public_headers) globally available (instead of having it in the user scope)  would help if we will have any other request that will need to use it  - but that can be tomorrow's problem :) 
> 

Hi, thx for your attention 
Actually user agent will not be detected .

2024-05-07 01:15 UTC, marek-knappe commented
@SaeidB 
```
Traceback (most recent call last):
  File "/Users/mknappe/Projects/inst/instagrapi/test.py", line 2, in <module>
    from instagrapi import Client
  File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/__init__.py", line 31, in <module>
    from instagrapi.mixins.public import (
  File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/mixins/public.py", line 83
    update_headers=None
                   ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```
Forgotten comma on that line.

2024-05-07 06:41 UTC, SaeidB commented
> @SaeidB
> 
> ```
> Traceback (most recent call last):
>   File "/Users/mknappe/Projects/inst/instagrapi/test.py", line 2, in <module>
>     from instagrapi import Client
>   File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/__init__.py", line 31, in <module>
>     from instagrapi.mixins.public import (
>   File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/mixins/public.py", line 83
>     update_headers=None
>                    ^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```
> 
> Forgotten comma on that line.
> 
> also:
> 
> ```
> name 'json' is not defined
> Traceback (most recent call last):
>   File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/mixins/user.py", line 194, in user_info_by_username
>     user = self.user_info_by_username_gql(username)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/mknappe/Projects/inst/instagrapi/instagrapi/mixins/user.py", line 146, in user_info_by_username_gql
>     data = extract_user_gql(json.loads(self.public_request(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers=temporary_public_headers))['data']['user'], update_headers=update_headers)
>                             ^^^^
> NameError: name 'json' is not defined
> ```
> 
> No Json imported for json.loads
> 
> Also:
> 
> ```
> TypeError: extract_user_gql() got an unexpected keyword argument 'update_headers'
> ```
> 
> Looks like user.py:147 has a update_headers after () from public request

hi, thanks for the mentioning 
the missing comma and missing json import has been fixed , for the last issue (unexpected keyword) i think you forgot to update public.py , can you update user.py and public.py and try again ?

2024-05-07 07:29 UTC, marek-knappe commented
@SaeidB  Works now, thanks, also I see that there are some conflicts so you need to resolve it before anyone will merge it

2024-07-18 12:27 UTC, ChristianJohnston97 commented
Will this fix be merged soon?

2024-08-01 11:28 UTC, SaeidB commented
> Will this fix be merged soon?

hello, i dunno really, but it works and you can add this to your lib even if it didn't merge

2024-08-15 14:02 UTC, chrisbuetti commented
The prior pull request still has an issue but this will work: https://github.com/subzeroid/instagrapi/pull/2003

2024-09-08 00:14 UTC, Brandon-Huu commented
> > Will this fix be merged soon?
> 
> hello, i dunno really, but it works and you can add this to your lib even if it didn't merge

how would I add this to my lib?

2024-09-14 06:20 UTC, sg-siddhant approved these changes

2024-11-11 07:01 UTC, SwallowData commented
Can it still be used now?

2024-11-11 17:20 UTC, SaeidB commented
> Can it still be used now?

hi, yes

2024-12-10 15:08 UTC, WarlaxZ commented
The only actual additional header you need is `X-Ig-App-Id: 936619743392459`

2024-12-10 15:48 UTC, WarlaxZ commented
This will get it working, however I've glossed over 2 fields that may be needed by other things

```
public_response = self.cl.public_request(f'https://www.instagram.com/api/v1/users/web_profile_info/?username={username}', headers={
    'X-Ig-App-Id': '936619743392459',
    "Accept": "application/json",
})
data_json = json.loads(public_response)['data']['user']
data_json["pinned_channels_info"] = {"pinned_channels_list": []}
for link in data_json["bio_links"]
    link["link_id"] = "set_me"
data = extract_user_gql(data_json)
return data
```

2025-07-09 15:37 UTC, merged

2025-07-09 15:37 UTC, subzeroid commented
@SaeidB thank you!